#!/var/bin/expect -d

# this code is to set how many iteration of checking to prompt the password
set count [lindex $argv 0]; 

# create infinite loop
set times 0;
spawn bash /root/node/genesisfiles/files/makeTransaction.sh
while {$count > 0} {
    expect "Please enter the password for wallet '<wallet name>': " {send -- "<wallet password>\r"}
    set count [expr $count-1];
}
expect eof
